// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-hCfQghWzKPwzj83-1Ex4gn14KebSBo',
    appId: '1:1065820753365:web:eeb5c8913372a5e820c15c',
    messagingSenderId: '1065820753365',
    projectId: 'skillbridge-ai-ce2f9',
    authDomain: 'skillbridge-ai-ce2f9.firebaseapp.com',
    storageBucket: 'skillbridge-ai-ce2f9.firebasestorage.app',
    measurementId: 'G-2D22RRSH76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBul9z7OfMBhI3efDTh5AkzE8n7tm-YB-c',
    appId: '1:1065820753365:android:a5fb253bc860d02c20c15c',
    messagingSenderId: '1065820753365',
    projectId: 'skillbridge-ai-ce2f9',
    storageBucket: 'skillbridge-ai-ce2f9.firebasestorage.app',
  );
}
